[package]
name = "rotated-vec"
version = "0.1.0"
authors = ["Tobin Baker <tobin.d.baker@gmail.com>"]
edition = "2018"

[lib]
name = "rotated_vec"
path = "src/lib.rs"
bench = false

[dev-dependencies]
is_sorted = "0.1.1"
proptest = "0.9"

[dependencies]
itertools = "0.8.0"
